"""add feedback table

Revision ID: 31d298494ae9
Revises: f99302e947d7
Create Date: 2026-09-17 14:18:27.709692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d298494ae9'
down_revision: Union[str, Sequence[str], None] = '0f6ccb630f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'session_id', name='uq_feedback_registration_session')
    )
    op.create_index(op.f('ix_feedback_event_id'), 'feedback', ['event_id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_rating'), 'feedback', ['rating'], unique=False)
    op.create_index(op.f('ix_feedback_registration_id'), 'feedback', ['registration_id'], unique=False)
    op.create_index(op.f('ix_feedback_session_id'), 'feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_feedback_speaker_id'), 'feedback', ['speaker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_speaker_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_session_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_registration_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_rating'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_event_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
