"""add feedback

Revision ID: e411bc9d9225
Revises: 0f6ccb630f3b
Create Date: 2026-09-17 15:23:39.014353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e411bc9d9225'
down_revision: Union[str, Sequence[str], None] = "31d298494ae9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_rating'), table_name='feedback')
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('REGISTRATION_CONFIRMATION', 'PAYMENT_SUCCESS', 'EVENT_REMINDER', 'SESSION_REMINDER', 'EVENT_CANCELLATION', 'TICKET_CONFIRMATION', 'CERTIFICATE_AVAILABLE', name='notificationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('REGISTRATION_CONFIRMATION', 'PAYMENT_SUCCESS', 'EVENT_REMINDER', 'SESSION_REMINDER', 'EVENT_CANCELLATION', 'TICKET_CONFIRMATION', 'CERTIFICATE_AVAILABLE', name='notificationtype'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.create_index(op.f('ix_feedback_rating'), 'feedback', ['rating'], unique=False)
    # ### end Alembic commands ###
